---
language: python
python: "2.7"

sudo: required
dist: trusty

before_install: cd tests

install:
- sudo apt-get update
- sudo add-apt-repository -y ppa:ansible/ansible
- sudo apt-get update
- sudo apt-get install -y ansible
- ansible --version
- ansible-galaxy install -r roles.txt

script:
- ansible-playbook -i inventory test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
