---
dist: xenial
language: python
python:
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install ansible molecule docker
script:
  - molecule converge
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
